version: '2'

volumes:
 db-data:
   external: false

services:
  db:
    image: postgres:9.5.12-alpine
    env_file: .env
    volumes:
      - $PWD/db-data:/var/lib/postgresql/data
    ports:
      - "15432:5432"
  webpacker:
    build: .
    command: bundle exec bin/webpack-dev-server
    volumes:
      - .:/confy
    ports:
      - "3035:3035"
    depends_on:
      - web
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/confy
    ports:
      - "3000:3000"
    depends_on:
      - db
